CREATE TABLE `search` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL DEFAULT '0',
  `username` VARCHAR(155) NOT NULL DEFAULT '',
  `gender` TINYINT(1) DEFAULT NULL,
  `age_from` INT(11) DEFAULT '0',
  `age_to` INT(11) DEFAULT '0',
  `within_from` DOUBLE DEFAULT NULL,
  `within_to` DOUBLE DEFAULT NULL,
  `height_from` DOUBLE DEFAULT NULL,
  `height_to` DOUBLE DEFAULT NULL,
  `education` VARCHAR(40) DEFAULT '',
  `ehtnicity` CHAR(30) DEFAULT '',
  `religion` CHAR(40) DEFAULT '',
  `children` INT(11) NOT NULL DEFAULT '0',
  `excercise` VARCHAR(255) DEFAULT NULL,
  `drink` VARCHAR(255) DEFAULT NULL,
  `smoke` VARCHAR(100) DEFAULT NULL,
  `is_online` INT(1) DEFAULT '0' COMMENT '0: Offline , 1: Online',
  `verified` INT(1) DEFAULT '1',
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `username` (`username`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8