CREATE TABLE `search` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL DEFAULT '0',
  `username` VARCHAR(155) NOT NULL DEFAULT '',
  `gender` TINYINT(1) DEFAULT NULL,
  `career` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(155) NOT NULL DEFAULT '',
  `password` VARCHAR(40) NOT NULL DEFAULT '',
  `joined` INT(10) DEFAULT '0',
  `role` CHAR(30) DEFAULT 'user',
  `ehtnicity` CHAR(30) DEFAULT '',
  `fname` VARCHAR(40) DEFAULT '',
  `lname` VARCHAR(40) DEFAULT '',
  `birthday` DATE DEFAULT NULL,
  `photo` VARCHAR(155) DEFAULT '',
  `address` VARCHAR(155) DEFAULT '',
  `education` VARCHAR(40) DEFAULT '',
  `religion` CHAR(40) DEFAULT '',
  `height` VARCHAR(100) DEFAULT NULL,
  `excercise` VARCHAR(255) DEFAULT NULL,
  `passion` VARCHAR(255) DEFAULT NULL,
  `goal` VARCHAR(255) DEFAULT NULL,
  `training` INT(11) NOT NULL DEFAULT '0',
  `gym` VARCHAR(255) NOT NULL,
  `about` TEXT NOT NULL,
  `diet` VARCHAR(255) NOT NULL,
  `children` INT(11) NOT NULL DEFAULT '0',
  `smoke` VARCHAR(100) DEFAULT NULL,
  `age` VARCHAR(255) NOT NULL,
  `relations` VARCHAR(255) DEFAULT NULL,
  `zipcode` VARCHAR(5) DEFAULT NULL,
  `latitude` VARCHAR(50) DEFAULT NULL,
  `longtitude` VARCHAR(50) DEFAULT NULL,
  `drink` VARCHAR(255) DEFAULT NULL,
  `status` INT(11) DEFAULT '0',
  `last_logged` DATETIME DEFAULT NULL,
  `language` VARCHAR(10) NOT NULL DEFAULT 'en',
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `verifyPhoto` INT(11) DEFAULT NULL,
  `is_online` INT(1) DEFAULT '0' COMMENT '0: Offline , 1: Online',
  `relations_look` VARCHAR(255) NOT NULL DEFAULT 'Casual',
  `gender_look` TEXT NOT NULL,
  `membership` INT(11) NOT NULL,
  `verified` INT(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `username` (`username`),
  KEY `email` (`email`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8